# Mod Properties
mod_version=3.0.31
maven_group=com.kangas
archives_base_name=kangas-shop-mod

# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2

# Dependencies
fabric_version=0.134.0+1.21.9