plugins {
    id 'fabric-loom' version '1.11-SNAPSHOT'
}

group = 'com.example.greekmyth'
archivesBaseName = 'greek-mythology'
version = '2.0.6'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.9'
    mappings 'net.fabricmc:yarn:1.21.9+build.1:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.16.14'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.131.0+1.21.8'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'com.mojang:brigadier:1.0.18'
}

loom {
    // Don't split environment source sets so client code can be included
} 