public class ahl {
   public static final zv<wx, ajh, ahl.a> a = ($$0, $$1) -> new zm<wx, ajh>() {
      public ajh a(wx $$0x) {
         if (!$$1.a()) {
            throw new wz("Not in creative mode");
         } else {
            return (ajh)$$0.decode($$0);
         }
      }

      public void a(wx $$0x, ajh $$1x) {
         if (!$$1.a()) {
            throw new xa("Not in creative mode");
         } else {
            $$0.encode($$0, $$1);
         }
      }
   };
   public static final aad<ahm, wx, ahl.a> b = aab.c(
      we.b,
      $$0 -> $$0.a(ahk.bl, aho.a)
         .a(ahk.bm, ahp.a)
         .a(ahk.bn, ajb.a)
         .a(ahk.bo, ahq.a)
         .a(ahk.bp, ahr.a)
         .a(ahk.bq, ahs.a)
         .a(ahk.br, aht.a)
         .a(ahk.bs, ahu.a)
         .a(ahk.bt, ahv.a)
         .a(ahk.bu, ahw.a)
         .a(ahk.bv, ahx.a)
         .a(ahk.bw, ahy.a)
         .a(ahk.bx, ahz.b)
         .a(aas.n, aau.a)
         .a(ahk.by, aia.a)
         .a(ahk.bz, aib.b)
         .a(ahk.bA, aic.a)
         .a(ahk.bB, aid.a)
         .a(ahk.bC, aie.a)
         .a(ahk.bD, aif.a)
         .a(acm.b, aco.a)
         .a(aas.o, aaw.a)
         .a(ahk.bE, aig.a)
         .a(ahk.bF, aih.a)
         .a(ahk.bG, aii.a)
         .a(ahk.bH, aij.a)
         .a(ahk.bI, aik.a)
         .a(aas.p, aax.a)
         .a(ahk.bJ, ail.a)
         .a(ahk.bK, aim.a.j)
         .a(ahk.bL, aim.b.j)
         .a(ahk.bM, aim.c.j)
         .a(ahk.bN, aim.d.j)
         .a(ahk.bO, ain.a)
         .a(ahk.bP, aio.a)
         .a(ahk.bQ, aip.a)
         .a(ahk.bR, aiq.a)
         .a(akv.b, akx.a)
         .a(ahk.bS, air.a)
         .a(ahk.bT, ais.a)
         .a(ahk.bU, ait.a)
         .a(ahk.bV, aiu.a)
         .a(ahk.bW, aiv.a)
         .a(ahk.bX, aiw.a)
         .a(aas.q, aay.a)
         .a(ahk.bY, aix.a)
         .a(ahk.bZ, aiy.a)
         .a(ahk.ca, aiz.a)
         .a(aas.r, aaz.a)
         .a(ahk.cb, aja.a)
         .a(ahk.cc, ajc.a)
         .a(ahk.cd, ajd.a)
         .a(ahk.ce, aje.a)
         .a(ahk.cf, ajf.a)
         .a(ahk.cg, ajg.a)
         .a(ahk.ch, ajh.a, a)
         .a(ahk.ci, aji.a)
         .a(ahk.cj, ajj.a)
         .a(ahk.ck, ajk.a)
         .a(ahk.cm, ajl.a)
         .a(ahk.cn, ajm.a)
         .a(ahk.co, ajn.a)
         .a(ahk.cl, ajo.a)
         .a(ahk.cp, ajp.a)
         .a(ahk.cq, ajq.a)
         .a(aas.s, aav.a)
   );
   public static final aac<acq, wx> c = aab.b(
      we.b,
      $$0 -> $$0.a(ahk.a, adb::new, new ada())
         .a(ahk.c, acr.a)
         .a(ahk.d, acs.a)
         .a(ahk.e, act.a)
         .a(ahk.f, acu.a)
         .a(ahk.g, acv.a)
         .a(ahk.h, acw.a)
         .a(ahk.i, acx.a)
         .a(ahk.j, acy.a)
         .a(ahk.k, acz.a)
         .a(ahk.l, adc.a)
         .a(ahk.m, add.a)
         .a(ahk.n, ade.b)
         .a(ahk.o, adf.a)
         .a(ahk.p, adg.a)
         .a(ahk.q, adh.a)
         .a(ahk.r, adi.a)
         .a(ahk.s, adj.a)
         .a(ahk.t, adk.a)
         .a(ahk.u, adl.a)
         .a(ahk.v, adm.a)
         .a(acm.a, acl.a)
         .a(ahk.w, adn.a)
         .a(ahk.x, ado.a)
         .a(aas.b, aag.a)
         .a(ahk.y, adp.a)
         .a(ahk.z, adq.a)
         .a(ahk.A, adr.a)
         .a(aas.d, aai.a)
         .a(ahk.B, ads.a)
         .a(ahk.C, adt.a)
         .a(ahk.D, adu.a)
         .a(ahk.E, adv.a)
         .a(ahk.F, adw.a)
         .a(ahk.G, adx.a)
         .a(ahk.H, ady.a)
         .a(ahk.I, adz.a)
         .a(ahk.J, aea.a)
         .a(aas.e, aaj.a)
         .a(ahk.K, aec.a)
         .a(ahk.L, aed.a)
         .a(ahk.M, aee.a)
         .a(ahk.N, aef.a)
         .a(ahk.O, aeh.a)
         .a(ahk.P, aei.a)
         .a(ahk.Q, aej.a)
         .a(ahk.R, aek.a.j)
         .a(ahk.S, aek.b.j)
         .a(ahk.T, ael.a)
         .a(ahk.U, aek.c.j)
         .a(ahk.V, aem.a)
         .a(ahk.W, aen.a)
         .a(ahk.X, aeo.a)
         .a(ahk.Y, aep.a)
         .a(aas.f, aak.a)
         .a(akv.a, aku.a)
         .a(ahk.Z, aeq.a)
         .a(ahk.aa, aer.a)
         .a(ahk.ab, aes.a)
         .a(ahk.ac, aet.a)
         .a(ahk.ad, aeu.b)
         .a(ahk.ae, aev.a)
         .a(ahk.af, aew.a)
         .a(ahk.ag, aex.a)
         .a(ahk.ah, aey.a)
         .a(ahk.ai, aez.a)
         .a(ahk.aj, afa.a)
         .a(ahk.ak, afc.a)
         .a(ahk.al, afd.a)
         .a(ahk.am, afe.a)
         .a(ahk.an, aff.a)
         .a(ahk.ao, afg.a)
         .a(ahk.cr, afh.a)
         .a(aas.g, aal.a)
         .a(aas.h, aam.b)
         .a(ahk.ap, afi.a)
         .a(ahk.aq, afj.a)
         .a(ahk.ar, afk.a)
         .a(ahk.as, afl.a)
         .a(ahk.at, afm.a)
         .a(ahk.au, afn.a)
         .a(ahk.av, afo.a)
         .a(ahk.aw, afp.a)
         .a(ahk.ax, afq.a)
         .a(ahk.ay, afr.a)
         .a(ahk.az, afs.a)
         .a(ahk.aA, aft.a)
         .a(ahk.aB, afu.a)
         .a(ahk.aC, afv.a)
         .a(ahk.cu, afw.a)
         .a(ahk.aD, afx.a)
         .a(ahk.aE, afy.a)
         .a(ahk.aF, afz.a)
         .a(ahk.aG, aga.a)
         .a(ahk.aH, agb.a)
         .a(ahk.aI, agc.a)
         .a(ahk.aJ, agd.a)
         .a(ahk.aK, age.a)
         .a(ahk.aL, agf.a)
         .a(ahk.aM, agg.a)
         .a(ahk.aN, agh.a)
         .a(ahk.cv, agi.a)
         .a(ahk.aO, agj.a)
         .a(ahk.aP, agk.a)
         .a(ahk.aQ, agl.a)
         .a(ahk.aR, agm.a)
         .a(ahk.aS, agn.a)
         .a(ahk.aT, ago.a)
         .a(ahk.aU, agp.a)
         .a(ahk.aV, agq.a)
         .a(ahk.aW, agr.a)
         .a(ahk.aX, ags.b)
         .a(ahk.aY, agt.a)
         .a(aas.k, aap.a)
         .a(ahk.aZ, agu.a)
         .a(ahk.ba, agv.a)
         .a(ahk.bb, agw.a)
         .a(ahk.bc, agx.a)
         .a(ahk.bd, agy.a)
         .a(ahk.be, agz.a)
         .a(ahk.cs, aha.a)
         .a(ahk.ct, ahb.a)
         .a(aas.l, aaq.a)
         .a(ahk.bf, ahd.a)
         .a(ahk.bg, ahe.a)
         .a(ahk.bh, ahf.a)
         .a(ahk.bi, ahg.a)
         .a(aas.m, aar.a)
         .a(ahk.bj, afb.a)
         .a(aas.c, aah.a)
         .a(aas.i, aan.a)
         .a(ahk.bk, ahc.a)
         .a(aas.a, aaf.b)
         .a(aas.j, aao.a)
   );

   public interface a {
      boolean a();
   }
}
