public class azj {
   public static final azi<dpz> a = a("mined", mm.e);
   public static final azi<dcr> b = a("crafted", mm.g);
   public static final azi<dcr> c = a("used", mm.g);
   public static final azi<dcr> d = a("broken", mm.g);
   public static final azi<dcr> e = a("picked_up", mm.g);
   public static final azi<dcr> f = a("dropped", mm.g);
   public static final azi<bzv<?>> g = a("killed", mm.f);
   public static final azi<bzv<?>> h = a("killed_by", mm.f);
   public static final azi<ame> i = a("custom", mm.k);
   public static final ame j = a("leave_game", azh.b);
   public static final ame k = a("play_time", azh.e);
   public static final ame l = a("total_world_time", azh.e);
   public static final ame m = a("time_since_death", azh.e);
   public static final ame n = a("time_since_rest", azh.e);
   public static final ame o = a("sneak_time", azh.e);
   public static final ame p = a("walk_one_cm", azh.d);
   public static final ame q = a("crouch_one_cm", azh.d);
   public static final ame r = a("sprint_one_cm", azh.d);
   public static final ame s = a("walk_on_water_one_cm", azh.d);
   public static final ame t = a("fall_one_cm", azh.d);
   public static final ame u = a("climb_one_cm", azh.d);
   public static final ame v = a("fly_one_cm", azh.d);
   public static final ame w = a("walk_under_water_one_cm", azh.d);
   public static final ame x = a("minecart_one_cm", azh.d);
   public static final ame y = a("boat_one_cm", azh.d);
   public static final ame z = a("pig_one_cm", azh.d);
   public static final ame A = a("happy_ghast_one_cm", azh.d);
   public static final ame B = a("horse_one_cm", azh.d);
   public static final ame C = a("aviate_one_cm", azh.d);
   public static final ame D = a("swim_one_cm", azh.d);
   public static final ame E = a("strider_one_cm", azh.d);
   public static final ame F = a("jump", azh.b);
   public static final ame G = a("drop", azh.b);
   public static final ame H = a("damage_dealt", azh.c);
   public static final ame I = a("damage_dealt_absorbed", azh.c);
   public static final ame J = a("damage_dealt_resisted", azh.c);
   public static final ame K = a("damage_taken", azh.c);
   public static final ame L = a("damage_blocked_by_shield", azh.c);
   public static final ame M = a("damage_absorbed", azh.c);
   public static final ame N = a("damage_resisted", azh.c);
   public static final ame O = a("deaths", azh.b);
   public static final ame P = a("mob_kills", azh.b);
   public static final ame Q = a("animals_bred", azh.b);
   public static final ame R = a("player_kills", azh.b);
   public static final ame S = a("fish_caught", azh.b);
   public static final ame T = a("talked_to_villager", azh.b);
   public static final ame U = a("traded_with_villager", azh.b);
   public static final ame V = a("eat_cake_slice", azh.b);
   public static final ame W = a("fill_cauldron", azh.b);
   public static final ame X = a("use_cauldron", azh.b);
   public static final ame Y = a("clean_armor", azh.b);
   public static final ame Z = a("clean_banner", azh.b);
   public static final ame aa = a("clean_shulker_box", azh.b);
   public static final ame ab = a("interact_with_brewingstand", azh.b);
   public static final ame ac = a("interact_with_beacon", azh.b);
   public static final ame ad = a("inspect_dropper", azh.b);
   public static final ame ae = a("inspect_hopper", azh.b);
   public static final ame af = a("inspect_dispenser", azh.b);
   public static final ame ag = a("play_noteblock", azh.b);
   public static final ame ah = a("tune_noteblock", azh.b);
   public static final ame ai = a("pot_flower", azh.b);
   public static final ame aj = a("trigger_trapped_chest", azh.b);
   public static final ame ak = a("open_enderchest", azh.b);
   public static final ame al = a("enchant_item", azh.b);
   public static final ame am = a("play_record", azh.b);
   public static final ame an = a("interact_with_furnace", azh.b);
   public static final ame ao = a("interact_with_crafting_table", azh.b);
   public static final ame ap = a("open_chest", azh.b);
   public static final ame aq = a("sleep_in_bed", azh.b);
   public static final ame ar = a("open_shulker_box", azh.b);
   public static final ame as = a("open_barrel", azh.b);
   public static final ame at = a("interact_with_blast_furnace", azh.b);
   public static final ame au = a("interact_with_smoker", azh.b);
   public static final ame av = a("interact_with_lectern", azh.b);
   public static final ame aw = a("interact_with_campfire", azh.b);
   public static final ame ax = a("interact_with_cartography_table", azh.b);
   public static final ame ay = a("interact_with_loom", azh.b);
   public static final ame az = a("interact_with_stonecutter", azh.b);
   public static final ame aA = a("bell_ring", azh.b);
   public static final ame aB = a("raid_trigger", azh.b);
   public static final ame aC = a("raid_win", azh.b);
   public static final ame aD = a("interact_with_anvil", azh.b);
   public static final ame aE = a("interact_with_grindstone", azh.b);
   public static final ame aF = a("target_hit", azh.b);
   public static final ame aG = a("interact_with_smithing_table", azh.b);

   private static ame a(String $$0, azh $$1) {
      ame $$2 = ame.b($$0);
      jy.a(mm.k, $$0, $$2);
      i.a($$2, $$1);
      return $$2;
   }

   private static <T> azi<T> a(String $$0, jy<T> $$1) {
      xo $$2 = xo.c("stat_type.minecraft." + $$0);
      return jy.a(mm.v, $$0, new azi<>($$1, $$2));
   }
}
