public interface bye {
   amd<byd> a = amd.a(mn.aR, ame.b("in_fire"));
   amd<byd> b = amd.a(mn.aR, ame.b("campfire"));
   amd<byd> c = amd.a(mn.aR, ame.b("lightning_bolt"));
   amd<byd> d = amd.a(mn.aR, ame.b("on_fire"));
   amd<byd> e = amd.a(mn.aR, ame.b("lava"));
   amd<byd> f = amd.a(mn.aR, ame.b("hot_floor"));
   amd<byd> g = amd.a(mn.aR, ame.b("in_wall"));
   amd<byd> h = amd.a(mn.aR, ame.b("cramming"));
   amd<byd> i = amd.a(mn.aR, ame.b("drown"));
   amd<byd> j = amd.a(mn.aR, ame.b("starve"));
   amd<byd> k = amd.a(mn.aR, ame.b("cactus"));
   amd<byd> l = amd.a(mn.aR, ame.b("fall"));
   amd<byd> m = amd.a(mn.aR, ame.b("ender_pearl"));
   amd<byd> n = amd.a(mn.aR, ame.b("fly_into_wall"));
   amd<byd> o = amd.a(mn.aR, ame.b("out_of_world"));
   amd<byd> p = amd.a(mn.aR, ame.b("generic"));
   amd<byd> q = amd.a(mn.aR, ame.b("magic"));
   amd<byd> r = amd.a(mn.aR, ame.b("wither"));
   amd<byd> s = amd.a(mn.aR, ame.b("dragon_breath"));
   amd<byd> t = amd.a(mn.aR, ame.b("dry_out"));
   amd<byd> u = amd.a(mn.aR, ame.b("sweet_berry_bush"));
   amd<byd> v = amd.a(mn.aR, ame.b("freeze"));
   amd<byd> w = amd.a(mn.aR, ame.b("stalagmite"));
   amd<byd> x = amd.a(mn.aR, ame.b("falling_block"));
   amd<byd> y = amd.a(mn.aR, ame.b("falling_anvil"));
   amd<byd> z = amd.a(mn.aR, ame.b("falling_stalactite"));
   amd<byd> A = amd.a(mn.aR, ame.b("sting"));
   amd<byd> B = amd.a(mn.aR, ame.b("mob_attack"));
   amd<byd> C = amd.a(mn.aR, ame.b("mob_attack_no_aggro"));
   amd<byd> D = amd.a(mn.aR, ame.b("player_attack"));
   amd<byd> E = amd.a(mn.aR, ame.b("arrow"));
   amd<byd> F = amd.a(mn.aR, ame.b("trident"));
   amd<byd> G = amd.a(mn.aR, ame.b("mob_projectile"));
   amd<byd> H = amd.a(mn.aR, ame.b("spit"));
   amd<byd> I = amd.a(mn.aR, ame.b("wind_charge"));
   amd<byd> J = amd.a(mn.aR, ame.b("fireworks"));
   amd<byd> K = amd.a(mn.aR, ame.b("fireball"));
   amd<byd> L = amd.a(mn.aR, ame.b("unattributed_fireball"));
   amd<byd> M = amd.a(mn.aR, ame.b("wither_skull"));
   amd<byd> N = amd.a(mn.aR, ame.b("thrown"));
   amd<byd> O = amd.a(mn.aR, ame.b("indirect_magic"));
   amd<byd> P = amd.a(mn.aR, ame.b("thorns"));
   amd<byd> Q = amd.a(mn.aR, ame.b("explosion"));
   amd<byd> R = amd.a(mn.aR, ame.b("player_explosion"));
   amd<byd> S = amd.a(mn.aR, ame.b("sonic_boom"));
   amd<byd> T = amd.a(mn.aR, ame.b("bad_respawn_point"));
   amd<byd> U = amd.a(mn.aR, ame.b("outside_border"));
   amd<byd> V = amd.a(mn.aR, ame.b("generic_kill"));
   amd<byd> W = amd.a(mn.aR, ame.b("mace_smash"));

   static void a(qq<byd> $$0) {
      $$0.a(a, new byd("inFire", 0.1F, bxz.d));
      $$0.a(b, new byd("inFire", 0.1F, bxz.d));
      $$0.a(c, new byd("lightningBolt", 0.1F));
      $$0.a(d, new byd("onFire", 0.0F, bxz.d));
      $$0.a(e, new byd("lava", 0.1F, bxz.d));
      $$0.a(f, new byd("hotFloor", 0.1F, bxz.d));
      $$0.a(g, new byd("inWall", 0.0F));
      $$0.a(h, new byd("cramming", 0.0F));
      $$0.a(i, new byd("drown", 0.0F, bxz.c));
      $$0.a(j, new byd("starve", 0.0F));
      $$0.a(k, new byd("cactus", 0.1F));
      $$0.a(l, new byd("fall", bya.b, 0.0F, bxz.a, byf.b));
      $$0.a(m, new byd("fall", bya.b, 0.0F, bxz.a, byf.b));
      $$0.a(n, new byd("flyIntoWall", 0.0F));
      $$0.a(o, new byd("outOfWorld", 0.0F));
      $$0.a(p, new byd("generic", 0.0F));
      $$0.a(q, new byd("magic", 0.0F));
      $$0.a(r, new byd("wither", 0.0F));
      $$0.a(s, new byd("dragonBreath", 0.0F));
      $$0.a(t, new byd("dryout", 0.1F));
      $$0.a(u, new byd("sweetBerryBush", 0.1F, bxz.e));
      $$0.a(v, new byd("freeze", 0.0F, bxz.f));
      $$0.a(w, new byd("stalagmite", 0.0F));
      $$0.a(x, new byd("fallingBlock", 0.1F));
      $$0.a(y, new byd("anvil", 0.1F));
      $$0.a(z, new byd("fallingStalactite", 0.1F));
      $$0.a(A, new byd("sting", 0.1F));
      $$0.a(B, new byd("mob", 0.1F));
      $$0.a(C, new byd("mob", 0.1F));
      $$0.a(D, new byd("player", 0.1F));
      $$0.a(E, new byd("arrow", 0.1F));
      $$0.a(F, new byd("trident", 0.1F));
      $$0.a(G, new byd("mob", 0.1F));
      $$0.a(H, new byd("mob", 0.1F));
      $$0.a(J, new byd("fireworks", 0.1F));
      $$0.a(L, new byd("onFire", 0.1F, bxz.d));
      $$0.a(K, new byd("fireball", 0.1F, bxz.d));
      $$0.a(M, new byd("witherSkull", 0.1F));
      $$0.a(N, new byd("thrown", 0.1F));
      $$0.a(O, new byd("indirectMagic", 0.0F));
      $$0.a(P, new byd("thorns", 0.1F, bxz.b));
      $$0.a(Q, new byd("explosion", bya.c, 0.1F));
      $$0.a(R, new byd("explosion.player", bya.c, 0.1F));
      $$0.a(S, new byd("sonic_boom", bya.c, 0.0F));
      $$0.a(T, new byd("badRespawnPoint", bya.c, 0.1F, bxz.a, byf.c));
      $$0.a(U, new byd("outsideBorder", 0.0F));
      $$0.a(V, new byd("genericKill", 0.0F));
      $$0.a(I, new byd("mob", 0.1F));
      $$0.a(W, new byd("mace_smash", 0.1F));
   }
}
