import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gqk {
   private static final gqr a = new gqr(0.008F);
   private static final gqr b = new gqr(1.0F);
   private static final gqr c = new gqr(0.5F);

   public static Map<gql, gqt> a() {
      Builder<gql, gqt> $$0 = ImmutableMap.builder();
      gqt $$1 = gqt.a(gnx.a(gqr.a, 0.0F), 64, 64);
      gqt $$2 = gqt.a(gnw.a(b), 64, 32);
      gqt $$3 = gqt.a(gnw.a(new gqr(1.02F)), 64, 32);
      gqt $$4 = gqt.a(gnw.a(c), 64, 32);
      gqt $$5 = goe.a();
      gqt $$6 = gpg.c();
      gqt $$7 = gqt.a(glq.a(gqr.a), 64, 64);
      gqt $$8 = gqt.a(glq.b(gqr.a), 64, 64);
      gqt $$9 = gni.a(false);
      gqt $$10 = gni.a(true);
      gqw $$11 = gqw.scaling(0.9375F);
      gqt $$12 = gny.a().a($$11);
      gqt $$13 = gmb.a();
      gqt $$14 = gmg.a();
      gqt $$15 = gmx.b();
      gqt $$16 = gmu.c();
      gqt $$17 = gmv.a();
      gqt $$18 = gmw.a(gqr.a);
      gqt $$19 = gnd.a();
      gqt $$20 = gqt.a(gnk.a(gqr.a), 64, 32);
      gqt $$21 = $$20.a(gnk.b);
      gqt $$22 = gqt.a(gnk.a(new gqr(0.01F)), 64, 32);
      gqt $$23 = gqt.a(gom.a(gqr.a), 64, 64);
      gqt $$24 = gqt.a(gol.a(), 64, 64);
      gqt $$25 = gpg.b();
      gqt $$26 = goc.a(gqr.a);
      gqt $$27 = goc.a(new gqr(0.5F));
      gqt $$28 = gpo.a();
      gqt $$29 = gnu.a();
      gqt $$30 = gnu.b();
      gqt $$31 = gpf.c();
      gqt $$32 = gqt.a(gpw.a(), 64, 64).a($$11);
      gqt $$33 = gpl.a();
      gqt $$34 = glw.a();
      gqt $$35 = gmo.a();
      gqt $$36 = gmp.c();
      gqt $$37 = gms.a();
      gqt $$38 = gnp.a();
      gqt $$39 = goh.a();
      gqt $$40 = gok.b(gqr.a);
      gqt $$41 = gok.b(new gqr(0.5F));
      gqt $$42 = gpa.a();
      gqt $$43 = goz.a();
      gqt $$44 = gpj.a();
      gqt $$45 = gpt.a();
      gqt $$46 = gpy.a();
      gqt $$47 = gqt.a(gqc.a(gqr.a), 64, 32);
      gqt $$48 = gqt.a(gqc.a(new gqr(0.2F)), 64, 32);
      gqt $$49 = gqe.a();
      gqt $$50 = glz.a();
      gqt $$51 = gly.a(c);
      gqt $$52 = gly.a(b);
      gqt $$53 = gnc.a(gqr.a);
      gqt $$54 = gnc.a(new gqr(0.25F));
      gqt $$55 = gpn.a();
      gqt $$56 = gna.a();
      gqt $$57 = goy.a();
      $$0.put(gqm.c, glu.a());
      $$0.put(gqm.d, $$34);
      $$0.put(gqm.e, $$34.a(glw.a));
      $$0.put(gqm.f, $$50);
      $$0.put(gqm.g, $$51);
      $$0.put(gqm.h, $$52);
      $$0.put(gqm.i, $$50.a(gnx.i));
      $$0.put(gqm.j, $$51.a(gnx.i));
      $$0.put(gqm.k, $$52.a(gnx.i));
      $$0.put(gqm.l, gma.a());
      $$0.put(gqm.m, $$13);
      $$0.put(gqm.n, $$13.a(gmb.b));
      $$0.put(gqm.q, gme.a(true));
      $$0.put(gqm.s, gme.a(false));
      $$0.put(gqm.r, gmd.a(true));
      $$0.put(gqm.t, gmd.a(false));
      $$0.put(gqm.u, gmf.a());
      $$0.put(gqm.v, gzz.d());
      $$0.put(gqm.w, gzz.c());
      $$0.put(gqm.x, $$14);
      $$0.put(gqm.y, $$14.a(gmg.a));
      $$0.put(gqm.z, gmh.a());
      $$0.put(gqm.A, gmi.a());
      $$0.put(gqm.D, gmj.a());
      $$0.put(gqm.E, gmk.c());
      $$0.put(gqm.F, gml.a());
      $$0.put(gqm.G, $$4);
      $$0.put(gqm.H, $$2);
      $$0.put(gqm.I, gqt.a(gnx.a(new gqr(0.2F), 0.0F), 64, 32));
      $$0.put(gqm.J, gmm.a());
      $$0.put(gqm.K, gmn.a(32, 32));
      $$0.put(gqm.L, gmn.a(128, 128));
      $$0.put(gqm.Q, $$20.a(gmq.a));
      $$0.put(gqm.R, $$21.a(gmq.a));
      $$0.put(gqm.T, $$22.a(gmq.a));
      $$0.put(gqm.S, $$22.a(gnk.b).a(gmq.a));
      $$0.put(gqm.M, $$35);
      $$0.put(gqm.N, $$35.a(gmo.a));
      $$0.put(gqm.O, $$36);
      $$0.put(gqm.P, $$36.a(gmo.a));
      $$0.put(gqm.U, $$33.a(gqw.scaling(0.7F)));
      $$0.put(gqm.X, gmr.a());
      $$0.put(gqm.Y, $$5);
      $$0.put(gqm.Z, $$37);
      $$0.put(gqm.aa, $$37.a(gms.c));
      $$0.put(gqm.ab, gmt.a());
      $$0.put(gqm.ac, $$16);
      $$0.put(gqm.ad, $$16.a(gms.c));
      $$0.put(gqm.ae, $$17);
      $$0.put(gqm.af, $$17.a(gmx.a));
      $$0.put(gqm.ag, $$18);
      $$0.put(gqm.ah, $$18.a(gok.a));
      $$0.put(gqm.ai, $$5);
      $$0.put(gqm.ak, hak.c());
      $$0.put(gqm.am, hak.d());
      $$0.put(gqm.al, hak.e());
      $$0.put(gqm.aj, hak.f());
      $$0.put(gqm.an, $$15);
      $$0.put(gqm.ao, $$15.a(gmx.a));
      $$0.put(gqm.ap, gmy.a());
      $$0.put(gqm.aq, gmz.a(gqr.a));
      $$0.put(gqm.ar, gmz.a(new gqr(2.0F)));
      $$0.put(gqm.as, $$6);
      $$0.put(gqm.av, hal.c());
      $$0.put(gqm.aw, hal.d());
      $$0.put(gqm.ax, $$56);
      $$0.put(gqm.ay, $$56.a(gna.a));
      $$0.put(gqm.az, gnb.a(0.87F));
      $$0.put(gqm.aA, gnb.b(0.87F));
      $$0.put(gqm.aB, gnb.a(0.87F, false));
      $$0.put(gqm.aC, gnb.a(0.87F, true));
      $$0.put(gqm.aD, gmr.c());
      $$0.put(gqm.aE, gmr.b());
      $$0.put(gqm.aF, gqg.a());
      $$0.put(gqm.aG, $$53);
      $$0.put(gqm.aL, $$4);
      $$0.put(gqm.aM, $$4);
      $$0.put(gqm.aN, $$54);
      $$0.put(gqm.aH, $$53.a(gnx.i));
      $$0.put(gqm.aI, $$4.a(gnx.i));
      $$0.put(gqm.aJ, $$4.a(gnx.i));
      $$0.put(gqm.aK, $$54.a(gnx.i));
      $$0.put(gqm.aO, gnq.b());
      $$0.put(gqm.aP, $$19);
      $$0.put(gqm.aQ, $$19.a(gnd.a));
      $$0.put(gqm.aR, gnf.a());
      $$0.put(gqm.aS, gng.a());
      $$0.put(gqm.aT, gqh.a());
      $$0.put(gqm.aU, gne.a());
      $$0.put(gqm.aV, $$12);
      $$0.put(gqm.aW, gnj.a());
      $$0.put(gqm.aX, gnl.a());
      $$0.put(gqm.aY, gnl.a().a(gnl.a));
      $$0.put(gqm.aZ, gnm.a());
      $$0.put(gqm.ba, $$5);
      $$0.put(gqm.bb, gnn.a());
      gqw $$58 = gqw.scaling(6.0F);
      $$0.put(gqm.bc, $$1.a($$58));
      $$0.put(gqm.bd, $$4.a($$58));
      $$0.put(gqm.be, $$2.a($$58));
      $$0.put(gqm.bf, $$55);
      $$0.put(gqm.bg, $$55.a(gpn.a));
      $$0.put(gqm.bh, $$38);
      $$0.put(gqm.bi, $$38.a(gnp.a));
      $$0.put(gqm.bj, gnq.a());
      $$0.put(gqm.bk, gns.a(false, gqr.a));
      $$0.put(gqm.bl, gns.a(true, gqr.a).a(gns.a));
      $$0.put(gqm.bm, gnr.a(false));
      $$0.put(gqm.bn, gnr.a(true).a(gns.a));
      $$0.put(gqm.bo, gns.a(false, new gqr(0.2F)));
      $$0.put(gqm.bp, gns.a(true, new gqr(0.2F)).a(gns.a));
      $$0.put(gqm.bq, $$29);
      $$0.put(gqm.br, $$30);
      $$0.put(gqm.bs, $$5);
      gqw $$59 = gqw.scaling(1.1F);
      $$0.put(gqm.bt, $$7.a($$59));
      $$0.put(gqm.bw, $$8.a($$59));
      $$0.put(gqm.bu, gqt.a(glq.a(new gqr(0.1F)), 64, 64).a($$59));
      $$0.put(gqm.bx, gqt.a(glq.b(new gqr(0.1F)), 64, 64).a($$59));
      $$0.put(gqm.bv, $$9.a($$59));
      $$0.put(gqm.by, $$10.a($$59));
      gqw $$60 = gqw.scaling(1.0625F);
      $$0.put(gqm.bz, $$1.a($$60));
      $$0.put(gqm.bD, $$4.a($$60));
      $$0.put(gqm.bE, $$2.a($$60));
      $$0.put(gqm.bA, $$1.a(gnx.i).a($$60));
      $$0.put(gqm.bB, $$4.a(gnx.i).a($$60));
      $$0.put(gqm.bC, $$2.a(gnx.i).a($$60));
      $$0.put(gqm.bF, $$12);
      $$0.put(gqm.bG, gnz.a());
      $$0.put(gqm.bJ, gob.a());
      $$0.put(gqm.bK, $$26);
      $$0.put(gqm.bL, $$26.a(goc.a));
      $$0.put(gqm.bN, $$27);
      $$0.put(gqm.bM, $$27.a(goc.a));
      $$0.put(gqm.bO, god.a());
      $$0.put(gqm.bP, goa.a());
      $$0.put(gqm.bS, $$5);
      $$0.put(gqm.bT, $$15);
      $$0.put(gqm.bU, $$15.a(gmx.a));
      $$0.put(gqm.bV, gnb.a(0.92F));
      $$0.put(gqm.bW, gnb.b(0.92F));
      $$0.put(gqm.bX, gnb.a(0.92F, false));
      $$0.put(gqm.bY, gnb.a(0.92F, true));
      $$0.put(gqm.cb, $$20);
      $$0.put(gqm.cc, $$21);
      $$0.put(gqm.cf, $$39);
      $$0.put(gqm.cg, $$39.a(goh.a));
      $$0.put(gqm.ch, goi.a());
      $$0.put(gqm.ci, goj.a());
      $$0.put(gqm.cj, $$40);
      $$0.put(gqm.cu, $$40.a(gok.a));
      $$0.put(gqm.cw, $$41);
      $$0.put(gqm.cv, $$41.a(gok.a));
      $$0.put(gqm.ck, $$23);
      $$0.put(gqm.cs, $$4);
      $$0.put(gqm.ct, $$3);
      $$0.put(gqm.co, $$23);
      $$0.put(gqm.cp, $$4);
      $$0.put(gqm.cq, $$3);
      $$0.put(gqm.cl, $$23.a(gnx.i));
      $$0.put(gqm.cm, $$4.a(gnx.i));
      $$0.put(gqm.cn, $$3.a(gnx.i));
      $$0.put(gqm.cr, $$24);
      $$0.put(gqm.cx, $$12);
      $$0.put(gqm.cy, gqt.a(gop.a(gqr.a, false), 64, 64));
      $$0.put(gqm.cA, goo.a());
      $$0.put(gqm.cz, gon.a());
      $$0.put(gqm.cB, $$25);
      $$0.put(gqm.cC, $$4);
      $$0.put(gqm.cD, $$2);
      $$0.put(gqm.cE, gqt.a(gop.a(gqr.a, true), 64, 64));
      $$0.put(gqm.cF, $$4);
      $$0.put(gqm.cG, $$2);
      $$0.put(gqm.cH, gpm.a());
      $$0.put(gqm.cI, goq.a(false));
      $$0.put(gqm.cJ, goq.a(true));
      $$0.put(gqm.cK, gor.a());
      $$0.put(gqm.cL, gos.a());
      $$0.put(gqm.cM, got.a());
      $$0.put(gqm.cN, gov.a(false));
      $$0.put(gqm.cO, gov.a(true));
      $$0.put(gqm.cP, gox.a());
      $$0.put(gqm.cQ, $$57);
      $$0.put(gqm.cS, $$57.a(goy.a));
      $$0.put(gqm.cR, $$57.a(goy.b));
      $$0.put(gqm.cT, $$42);
      $$0.put(gqm.cU, $$42.a(gpa.a));
      $$0.put(gqm.cW, $$43);
      $$0.put(gqm.cV, $$43.a(gpa.a));
      $$0.put(gqm.cX, $$42);
      $$0.put(gqm.cY, $$42.a(gpa.a));
      $$0.put(gqm.cZ, gpb.a());
      $$0.put(gqm.da, gpd.a());
      $$0.put(gqm.db, gpd.b());
      $$0.put(gqm.dc, gpc.a());
      $$0.put(gqm.dd, gpe.a());
      $$0.put(gqm.de, $$31);
      $$0.put(gqm.dj, $$4);
      $$0.put(gqm.dk, $$2);
      $$0.put(gqm.df, $$7);
      $$0.put(gqm.dg, $$8);
      $$0.put(gqm.dh, $$9);
      $$0.put(gqm.di, $$10);
      $$0.put(gqm.dl, $$6);
      $$0.put(gqm.dm, gpi.b());
      $$0.put(gqm.dn, gpi.a());
      $$0.put(gqm.do, $$44);
      $$0.put(gqm.dp, $$44.a(gpj.a));
      $$0.put(gqm.dq, gpk.a());
      $$0.put(gqm.dr, $$5);
      $$0.put(gqm.ds, $$33);
      $$0.put(gqm.dv, $$55);
      $$0.put(gqm.dw, $$55.a(gpn.a));
      $$0.put(gqm.dx, $$31);
      $$0.put(gqm.dy, $$4);
      $$0.put(gqm.dz, $$2);
      $$0.put(gqm.dA, gqt.a(gnx.a(new gqr(0.25F), 0.0F), 64, 32));
      $$0.put(gqm.dB, $$28);
      $$0.put(gqm.dC, $$28);
      $$0.put(gqm.dD, $$28.a(gpo.a));
      $$0.put(gqm.dE, $$28.a(gpo.a));
      $$0.put(gqm.dF, gpp.a());
      $$0.put(gqm.dG, $$5);
      $$0.put(gqm.dH, $$26);
      $$0.put(gqm.dI, $$26.a(goc.a));
      $$0.put(gqm.dJ, gpq.a());
      $$0.put(gqm.dK, gps.a(gqr.a));
      $$0.put(gqm.dL, gps.a(a));
      $$0.put(gqm.dM, gpr.a(gqr.a));
      $$0.put(gqm.dN, gpr.a(a));
      $$0.put(gqm.dO, $$45);
      $$0.put(gqm.dP, $$45.a(gpt.a));
      $$0.put(gqm.dQ, gpu.a());
      $$0.put(gqm.dR, $$32);
      $$0.put(gqm.dS, $$32.a(gpw.a));
      $$0.put(gqm.dT, $$12);
      $$0.put(gqm.dV, gpx.a());
      $$0.put(gqm.dW, $$46);
      $$0.put(gqm.dX, $$46.a(gmx.a));
      $$0.put(gqm.dU, $$32);
      $$0.put(gqm.dY, gpz.a());
      $$0.put(gqm.dZ, gqa.a().a($$11));
      $$0.put(gqm.ea, gqb.a(gqr.a));
      $$0.put(gqm.eb, gqb.a(c));
      $$0.put(gqm.eg, hhj.a());
      gqw $$61 = gqw.scaling(1.2F);
      $$0.put(gqm.ec, $$31.a($$61));
      $$0.put(gqm.ed, $$4.a($$61));
      $$0.put(gqm.ee, $$2.a($$61));
      $$0.put(gqm.ef, $$6);
      $$0.put(gqm.eh, $$47);
      $$0.put(gqm.ei, $$48);
      $$0.put(gqm.ej, $$47.a(gqc.a));
      $$0.put(gqm.ek, $$48.a(gqc.a));
      $$0.put(gqm.el, $$29);
      $$0.put(gqm.em, $$30);
      $$0.put(gqm.en, $$1);
      $$0.put(gqm.ew, $$4);
      $$0.put(gqm.ex, $$2);
      $$0.put(gqm.eo, $$1.a(gnx.i));
      $$0.put(gqm.ep, $$4.a(gnx.i));
      $$0.put(gqm.eq, $$2.a(gnx.i));
      $$0.put(gqm.er, $$25);
      $$0.put(gqm.es, $$7);
      $$0.put(gqm.et, $$8);
      $$0.put(gqm.eu, $$9);
      $$0.put(gqm.ev, $$10);
      $$0.put(gqm.ey, $$49);
      $$0.put(gqm.eC, gqe.a(c));
      $$0.put(gqm.eD, gqe.a(b));
      $$0.put(gqm.ez, $$49.a(gnx.i));
      $$0.put(gqm.eA, gqe.a(c).a(gnx.i));
      $$0.put(gqm.eB, gqe.a(b).a(gnx.i));
      $$0.put(gqm.eE, $$23);
      $$0.put(gqm.eI, $$4);
      $$0.put(gqm.eJ, $$3);
      $$0.put(gqm.eF, $$23.a(gnx.i));
      $$0.put(gqm.eG, $$4.a(gnx.i));
      $$0.put(gqm.eH, $$3.a(gnx.i));
      $$0.put(gqm.p, gow.a());
      $$0.put(gqm.o, gow.b());
      gqt $$62 = gmk.a();
      gqt $$63 = gmk.b();
      $$0.put(gqm.bZ, $$62);
      $$0.put(gqm.ca, $$63);
      $$0.put(gqm.dt, $$62);
      $$0.put(gqm.du, $$63);
      $$0.put(gqm.B, $$62);
      $$0.put(gqm.C, $$63);
      $$0.put(gqm.bH, $$62);
      $$0.put(gqm.bI, $$63);
      $$0.put(gqm.a, $$62);
      $$0.put(gqm.b, $$63);
      $$0.put(gqm.V, $$62);
      $$0.put(gqm.W, $$63);
      $$0.put(gqm.at, $$62);
      $$0.put(gqm.au, $$63);
      $$0.put(gqm.cd, $$62);
      $$0.put(gqm.ce, $$63);
      $$0.put(gqm.bQ, $$62);
      $$0.put(gqm.bR, $$63);
      gqt $$64 = har.a(true);
      gqt $$65 = har.a(false);
      efp.a().forEach($$3x -> {
         $$0.put(gqm.a($$3x), $$64);
         $$0.put(gqm.b($$3x), $$65);

         for (han.a $$4x : han.a.values()) {
            gqt $$5x = han.a($$4x);
            $$0.put(gqm.a($$3x, $$4x), $$5x);
         }
      });
      ImmutableMap<gql, gqt> $$66 = $$0.build();
      List<gql> $$67 = gqm.a().filter($$1x -> !$$66.containsKey($$1x)).collect(Collectors.toList());
      if (!$$67.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$67);
      } else {
         return $$66;
      }
   }
}
