import com.google.common.collect.Maps;
import java.util.Map;

public class gxe {
   private static final Map<dpz, hba> a = ag.a(Maps.newHashMap(), $$0 -> {
      hba $$1 = hba.e;
      $$0.put(dqb.gh, $$1);
      hba $$2 = hba.b;
      $$0.put(dqb.i, $$2);
      $$0.put(dqb.fo, $$2);
      $$0.put(dqb.fq, $$2);
      $$0.put(dqb.gg, $$2);
      $$0.put(dqb.hD, $$2);
      $$0.put(dqb.fp, $$2);
      $$0.put(dqb.aN, $$2);
      $$0.put(dqb.aK, $$2);
      $$0.put(dqb.aL, $$2);
      $$0.put(dqb.aO, $$2);
      $$0.put(dqb.aP, $$2);
      $$0.put(dqb.aM, $$2);
      $$0.put(dqb.aQ, $$2);
      $$0.put(dqb.aR, $$2);
      $$0.put(dqb.aT, $$2);
      $$0.put(dqb.aU, $$2);
      $$0.put(dqb.ag, $$2);
      $$0.put(dqb.aS, $$2);
      hba $$3 = hba.c;
      $$0.put(dqb.z, $$3);
      $$0.put(dqb.A, $$3);
      $$0.put(dqb.B, $$3);
      $$0.put(dqb.C, $$3);
      $$0.put(dqb.D, $$3);
      $$0.put(dqb.E, $$3);
      $$0.put(dqb.F, $$3);
      $$0.put(dqb.G, $$3);
      $$0.put(dqb.aX, $$3);
      $$0.put(dqb.bg, $$3);
      $$0.put(dqb.bh, $$3);
      $$0.put(dqb.bi, $$3);
      $$0.put(dqb.bj, $$3);
      $$0.put(dqb.bk, $$3);
      $$0.put(dqb.bl, $$3);
      $$0.put(dqb.bm, $$3);
      $$0.put(dqb.bn, $$3);
      $$0.put(dqb.bo, $$3);
      $$0.put(dqb.bp, $$3);
      $$0.put(dqb.bq, $$3);
      $$0.put(dqb.br, $$3);
      $$0.put(dqb.bs, $$3);
      $$0.put(dqb.bt, $$3);
      $$0.put(dqb.bu, $$3);
      $$0.put(dqb.bv, $$3);
      $$0.put(dqb.bw, $$3);
      $$0.put(dqb.bx, $$3);
      $$0.put(dqb.bz, $$3);
      $$0.put(dqb.bA, $$3);
      $$0.put(dqb.bB, $$3);
      $$0.put(dqb.bD, $$3);
      $$0.put(dqb.bC, $$3);
      $$0.put(dqb.bE, $$3);
      $$0.put(dqb.bF, $$3);
      $$0.put(dqb.bG, $$3);
      $$0.put(dqb.bH, $$3);
      $$0.put(dqb.cb, $$3);
      $$0.put(dqb.ui, $$3);
      $$0.put(dqb.uj, $$3);
      $$0.put(dqb.cd, $$3);
      $$0.put(dqb.ce, $$3);
      $$0.put(dqb.cf, $$3);
      $$0.put(dqb.cg, $$3);
      $$0.put(dqb.ch, $$3);
      $$0.put(dqb.ci, $$3);
      $$0.put(dqb.cj, $$3);
      $$0.put(dqb.ck, $$3);
      $$0.put(dqb.cl, $$3);
      $$0.put(dqb.cm, $$3);
      $$0.put(dqb.cn, $$3);
      $$0.put(dqb.co, $$3);
      $$0.put(dqb.cp, $$3);
      $$0.put(dqb.cq, $$3);
      $$0.put(dqb.cz, $$3);
      $$0.put(dqb.cA, $$3);
      $$0.put(dqb.er, $$3);
      $$0.put(dqb.es, $$3);
      $$0.put(dqb.cB, $$3);
      $$0.put(dqb.cC, $$3);
      $$0.put(dqb.cD, $$3);
      $$0.put(dqb.uc, $$3);
      $$0.put(dqb.ud, $$3);
      $$0.put(dqb.cH, $$3);
      $$0.put(dqb.cM, $$3);
      $$0.put(dqb.cZ, $$3);
      $$0.put(dqb.da, $$3);
      $$0.put(dqb.db, $$3);
      $$0.put(dqb.dN, $$3);
      $$0.put(dqb.ea, $$3);
      $$0.put(dqb.eb, $$3);
      $$0.put(dqb.eg, $$3);
      $$0.put(dqb.ej, $$3);
      $$0.put(dqb.ey, $$3);
      $$0.put(dqb.eP, $$3);
      $$0.put(dqb.eQ, $$3);
      $$0.put(dqb.eR, $$3);
      $$0.put(dqb.eS, $$3);
      $$0.put(dqb.eT, $$3);
      $$0.put(dqb.eU, $$3);
      $$0.put(dqb.eV, $$3);
      $$0.put(dqb.eW, $$3);
      $$0.put(dqb.pt, $$3);
      $$0.put(dqb.pu, $$3);
      $$0.put(dqb.eX, $$3);
      $$0.put(dqb.eY, $$3);
      $$0.put(dqb.sD, $$3);
      $$0.put(dqb.sE, $$3);
      $$0.put(dqb.sG, $$3);
      $$0.put(dqb.sF, $$3);
      $$0.put(dqb.sH, $$3);
      $$0.put(dqb.sI, $$3);
      $$0.put(dqb.sK, $$3);
      $$0.put(dqb.sJ, $$3);
      $$0.put(dqb.ft, $$3);
      $$0.put(dqb.fu, $$3);
      $$0.put(dqb.fv, $$3);
      $$0.put(dqb.fw, $$3);
      $$0.put(dqb.fx, $$3);
      $$0.put(dqb.ug, $$3);
      $$0.put(dqb.uh, $$3);
      $$0.put(dqb.fy, $$3);
      $$0.put(dqb.fz, $$3);
      $$0.put(dqb.fF, $$3);
      $$0.put(dqb.fP, $$3);
      $$0.put(dqb.fR, $$3);
      $$0.put(dqb.gb, $$3);
      $$0.put(dqb.gn, $$3);
      $$0.put(dqb.gq, $$3);
      $$0.put(dqb.gs, $$3);
      $$0.put(dqb.gt, $$3);
      $$0.put(dqb.gu, $$3);
      $$0.put(dqb.gv, $$3);
      $$0.put(dqb.gw, $$3);
      $$0.put(dqb.gx, $$3);
      $$0.put(dqb.gy, $$3);
      $$0.put(dqb.gz, $$3);
      $$0.put(dqb.gA, $$3);
      $$0.put(dqb.gB, $$3);
      $$0.put(dqb.gC, $$3);
      $$0.put(dqb.gD, $$3);
      $$0.put(dqb.uk, $$3);
      $$0.put(dqb.ul, $$3);
      $$0.put(dqb.gE, $$3);
      $$0.put(dqb.gF, $$3);
      $$0.put(dqb.gG, $$3);
      $$0.put(dqb.gH, $$3);
      $$0.put(dqb.gI, $$3);
      $$0.put(dqb.gJ, $$3);
      $$0.put(dqb.gK, $$3);
      $$0.put(dqb.gL, $$3);
      $$0.put(dqb.gM, $$3);
      $$0.put(dqb.gN, $$3);
      $$0.put(dqb.gO, $$3);
      $$0.put(dqb.gP, $$3);
      $$0.put(dqb.gQ, $$3);
      $$0.put(dqb.gR, $$3);
      $$0.put(dqb.gS, $$3);
      $$0.put(dqb.tT, $$3);
      $$0.put(dqb.tU, $$3);
      $$0.put(dqb.gr, $$3);
      $$0.put(dqb.gT, $$3);
      $$0.put(dqb.gU, $$3);
      $$0.put(dqb.hz, $$3);
      $$0.put(dqb.hI, $$3);
      $$0.put(dqb.iA, $$3);
      $$0.put(dqb.jf, $$3);
      $$0.put(dqb.jg, $$3);
      $$0.put(dqb.jh, $$3);
      $$0.put(dqb.ji, $$3);
      $$0.put(dqb.jj, $$3);
      $$0.put(dqb.jk, $$3);
      $$0.put(dqb.kQ, $$3);
      $$0.put(dqb.kR, $$3);
      $$0.put(dqb.kS, $$3);
      $$0.put(dqb.kT, $$3);
      $$0.put(dqb.kU, $$3);
      $$0.put(dqb.kV, $$3);
      $$0.put(dqb.kW, $$3);
      $$0.put(dqb.kX, $$3);
      $$0.put(dqb.kY, $$3);
      $$0.put(dqb.sv, $$3);
      $$0.put(dqb.sw, $$3);
      $$0.put(dqb.sy, $$3);
      $$0.put(dqb.sx, $$3);
      $$0.put(dqb.sz, $$3);
      $$0.put(dqb.sA, $$3);
      $$0.put(dqb.sC, $$3);
      $$0.put(dqb.sB, $$3);
      $$0.put(dqb.kZ, $$3);
      $$0.put(dqb.la, $$3);
      $$0.put(dqb.lb, $$3);
      $$0.put(dqb.cc, $$3);
      $$0.put(dqb.lg, $$3);
      $$0.put(dqb.li, $$3);
      $$0.put(dqb.lh, $$3);
      $$0.put(dqb.lj, $$3);
      $$0.put(dqb.mI, $$3);
      $$0.put(dqb.mJ, $$3);
      $$0.put(dqb.mL, $$3);
      $$0.put(dqb.mY, $$3);
      $$0.put(dqb.mZ, $$3);
      $$0.put(dqb.na, $$3);
      $$0.put(dqb.nb, $$3);
      $$0.put(dqb.nc, $$3);
      $$0.put(dqb.nd, $$3);
      $$0.put(dqb.ne, $$3);
      $$0.put(dqb.nf, $$3);
      $$0.put(dqb.ng, $$3);
      $$0.put(dqb.nh, $$3);
      $$0.put(dqb.ni, $$3);
      $$0.put(dqb.nj, $$3);
      $$0.put(dqb.nk, $$3);
      $$0.put(dqb.nl, $$3);
      $$0.put(dqb.nm, $$3);
      $$0.put(dqb.nn, $$3);
      $$0.put(dqb.no, $$3);
      $$0.put(dqb.np, $$3);
      $$0.put(dqb.nq, $$3);
      $$0.put(dqb.nr, $$3);
      $$0.put(dqb.ns, $$3);
      $$0.put(dqb.nt, $$3);
      $$0.put(dqb.nu, $$3);
      $$0.put(dqb.nv, $$3);
      $$0.put(dqb.nw, $$3);
      $$0.put(dqb.nx, $$3);
      $$0.put(dqb.ny, $$3);
      $$0.put(dqb.nz, $$3);
      $$0.put(dqb.nA, $$3);
      $$0.put(dqb.nB, $$3);
      $$0.put(dqb.nC, $$3);
      $$0.put(dqb.nE, $$3);
      $$0.put(dqb.nF, $$3);
      $$0.put(dqb.nG, $$3);
      $$0.put(dqb.nH, $$3);
      $$0.put(dqb.oz, $$3);
      $$0.put(dqb.oJ, $$3);
      $$0.put(dqb.oL, $$3);
      $$0.put(dqb.oM, $$3);
      $$0.put(dqb.oN, $$3);
      $$0.put(dqb.oO, $$3);
      $$0.put(dqb.oP, $$3);
      $$0.put(dqb.pg, $$3);
      $$0.put(dqb.ph, $$3);
      $$0.put(dqb.pi, $$3);
      $$0.put(dqb.pj, $$3);
      $$0.put(dqb.oY, $$3);
      $$0.put(dqb.pe, $$3);
      $$0.put(dqb.oV, $$3);
      $$0.put(dqb.pk, $$3);
      $$0.put(dqb.oX, $$3);
      $$0.put(dqb.pV, $$3);
      $$0.put(dqb.pW, $$3);
      $$0.put(dqb.pX, $$3);
      $$0.put(dqb.pY, $$3);
      $$0.put(dqb.pB, $$3);
      $$0.put(dqb.pC, $$3);
      $$0.put(dqb.tc, $$3);
      $$0.put(dqb.rh, $$3);
      $$0.put(dqb.rg, $$3);
      $$0.put(dqb.rf, $$3);
      $$0.put(dqb.re, $$3);
      $$0.put(dqb.tb, $$3);
      $$0.put(dqb.te, $$3);
      $$0.put(dqb.tf, $$3);
      $$0.put(dqb.tg, $$3);
      $$0.put(dqb.ti, $$3);
      $$0.put(dqb.th, $$3);
      $$0.put(dqb.tk, $$3);
      $$0.put(dqb.tl, $$3);
      $$0.put(dqb.tm, $$3);
      $$0.put(dqb.to, $$3);
      $$0.put(dqb.tp, $$3);
      $$0.put(dqb.tq, $$3);
      $$0.put(dqb.tr, $$3);
      $$0.put(dqb.rz, $$3);
      $$0.put(dqb.rA, $$3);
      $$0.put(dqb.rC, $$3);
      $$0.put(dqb.rE, $$3);
      $$0.put(dqb.H, $$3);
      $$0.put(dqb.tY, $$3);
      $$0.put(dqb.sL, $$3);
      $$0.put(dqb.sM, $$3);
      $$0.put(dqb.sN, $$3);
      $$0.put(dqb.sO, $$3);
      $$0.put(dqb.sP, $$3);
      $$0.put(dqb.sQ, $$3);
      $$0.put(dqb.sR, $$3);
      $$0.put(dqb.sS, $$3);
      $$0.put(dqb.um, $$3);
      $$0.put(dqb.eh, $$3);
      hba $$4 = hba.d;
      $$0.put(dqb.ee, $$4);
      $$0.put(dqb.eu, $$4);
      $$0.put(dqb.ez, $$4);
      $$0.put(dqb.eA, $$4);
      $$0.put(dqb.eB, $$4);
      $$0.put(dqb.eC, $$4);
      $$0.put(dqb.eD, $$4);
      $$0.put(dqb.eE, $$4);
      $$0.put(dqb.eF, $$4);
      $$0.put(dqb.eG, $$4);
      $$0.put(dqb.eH, $$4);
      $$0.put(dqb.eI, $$4);
      $$0.put(dqb.eJ, $$4);
      $$0.put(dqb.eK, $$4);
      $$0.put(dqb.eL, $$4);
      $$0.put(dqb.eM, $$4);
      $$0.put(dqb.eN, $$4);
      $$0.put(dqb.eO, $$4);
      $$0.put(dqb.ia, $$4);
      $$0.put(dqb.ib, $$4);
      $$0.put(dqb.ic, $$4);
      $$0.put(dqb.id, $$4);
      $$0.put(dqb.ie, $$4);
      $$0.put(dqb.if, $$4);
      $$0.put(dqb.ig, $$4);
      $$0.put(dqb.ih, $$4);
      $$0.put(dqb.ii, $$4);
      $$0.put(dqb.ij, $$4);
      $$0.put(dqb.ik, $$4);
      $$0.put(dqb.il, $$4);
      $$0.put(dqb.im, $$4);
      $$0.put(dqb.in, $$4);
      $$0.put(dqb.io, $$4);
      $$0.put(dqb.ip, $$4);
      $$0.put(dqb.ix, $$4);
      $$0.put(dqb.pP, $$4);
      $$0.put(dqb.lo, $$4);
      $$0.put(dqb.nK, $$4);
      $$0.put(dqb.rx, $$4);
   });
   private static final Map<fak, hba> b = ag.a(Maps.newHashMap(), $$0 -> {
      $$0.put(fam.b, hba.d);
      $$0.put(fam.c, hba.d);
   });
   private static boolean c;

   public static hba a(eeb $$0) {
      dpz $$1 = $$0.b();
      if ($$1 instanceof duq) {
         return c ? hba.b : hba.a;
      } else {
         hba $$2 = a.get($$1);
         return $$2 != null ? $$2 : hba.a;
      }
   }

   public static gxz b(eeb $$0) {
      dpz $$1 = $$0.b();
      if ($$1 instanceof duq) {
         return c ? gxz.e() : gxz.d();
      } else {
         hba $$2 = a.get($$1);
         if ($$2 != null) {
            return switch ($$2) {
               case a -> gxz.d();
               case b -> gxz.e();
               case c -> gxz.f();
               case d -> gxz.g();
               case e -> gxz.s();
            };
         } else {
            return gxz.d();
         }
      }
   }

   public static gxz c(eeb $$0) {
      hba $$1 = a($$0);
      return $$1 == hba.d ? gyi.j() : gyi.i();
   }

   public static gxz a(dcv $$0) {
      if ($$0.h() instanceof dbd $$2) {
         dpz $$3 = $$2.c();
         return c($$3.m());
      } else {
         return gyi.j();
      }
   }

   public static hba a(fal $$0) {
      hba $$1 = b.get($$0.a());
      return $$1 != null ? $$1 : hba.a;
   }

   public static void a(boolean $$0) {
      c = $$0;
   }
}
