import com.mojang.serialization.Codec;
import java.util.List;
import java.util.function.UnaryOperator;

public class kq {
   static final bbg a = new bbg(512);
   public static final kp<dfd> b = a("custom_data", $$0 -> $$0.a(dfd.b));
   public static final kp<Integer> c = a("max_stack_size", $$0 -> $$0.a(bbi.a(1, 99)).a(zk.h));
   public static final kp<Integer> d = a("max_damage", $$0 -> $$0.a(bbi.p).a(zk.h));
   public static final kp<Integer> e = a("damage", $$0 -> $$0.a(bbi.o).a(zk.h));
   public static final kp<bdk> f = a("unbreakable", $$0 -> $$0.a(bdk.b).a(bdk.c));
   public static final kp<xo> g = a("custom_name", $$0 -> $$0.a(xq.a).a(xq.b).a());
   public static final kp<xo> h = a("item_name", $$0 -> $$0.a(xq.a).a(xq.b).a());
   public static final kp<ame> i = a("item_model", $$0 -> $$0.a(ame.a).a(ame.b).a());
   public static final kp<dfo> j = a("lore", $$0 -> $$0.a(dfo.c).a(dfo.d).a());
   public static final kp<ddr> k = a("rarity", $$0 -> $$0.a(ddr.e).a(ddr.g));
   public static final kp<djo> l = a("enchantments", $$0 -> $$0.a(djo.b).a(djo.c).a());
   public static final kp<daw> m = a("can_place_on", $$0 -> $$0.a(daw.a).a(daw.b).a());
   public static final kp<daw> n = a("can_break", $$0 -> $$0.a(daw.a).a(daw.b).a());
   public static final kp<dfm> o = a("attribute_modifiers", $$0 -> $$0.a(dfm.b).a(dfm.c).a());
   public static final kp<dfe> p = a("custom_model_data", $$0 -> $$0.a(dfe.b).a(dfe.c));
   public static final kp<dfz> q = a("tooltip_display", $$0 -> $$0.a(dfz.a).a(dfz.b).a());
   public static final kp<Integer> r = a("repair_cost", $$0 -> $$0.a(bbi.o).a(zk.h));
   public static final kp<bdk> s = a("creative_slot_lock", $$0 -> $$0.a(bdk.c));
   public static final kp<Boolean> t = a("enchantment_glint_override", $$0 -> $$0.a(Codec.BOOL).a(zk.b));
   public static final kp<bdk> u = a("intangible_projectile", $$0 -> $$0.a(bdk.b));
   public static final kp<cyj> v = a("food", $$0 -> $$0.a(cyj.a).a(cyj.b).a());
   public static final kp<dfa> w = a("consumable", $$0 -> $$0.a(dfa.b).a(dfa.c).a());
   public static final kp<dgc> x = a("use_remainder", $$0 -> $$0.a(dgc.a).a(dgc.b).a());
   public static final kp<dgb> y = a("use_cooldown", $$0 -> $$0.a(dgb.a).a(dgb.b).a());
   public static final kp<dff> z = a("damage_resistant", $$0 -> $$0.a(dff.a).a(dff.b).a());
   public static final kp<dfy> A = a("tool", $$0 -> $$0.a(dfy.a).a(dfy.b).a());
   public static final kp<dgd> B = a("weapon", $$0 -> $$0.a(dgd.b).a(dgd.c).a());
   public static final kp<djg> C = a("enchantable", $$0 -> $$0.a(djg.a).a(djg.b).a());
   public static final kp<dle> D = a("equippable", $$0 -> $$0.a(dle.a).a(dle.b).a());
   public static final kp<djq> E = a("repairable", $$0 -> $$0.a(djq.a).a(djq.b).a());
   public static final kp<bdk> F = a("glider", $$0 -> $$0.a(bdk.b).a(bdk.c));
   public static final kp<ame> G = a("tooltip_style", $$0 -> $$0.a(ame.a).a(ame.b).a());
   public static final kp<dfg> H = a("death_protection", $$0 -> $$0.a(dfg.a).a(dfg.b).a());
   public static final kp<dew> I = a("blocks_attacks", $$0 -> $$0.a(dew.a).a(dew.b).a());
   public static final kp<djo> J = a("stored_enchantments", $$0 -> $$0.a(djo.b).a(djo.c).a());
   public static final kp<dfi> K = a("dyed_color", $$0 -> $$0.a(dfi.a).a(dfi.b));
   public static final kp<dfr> L = a("map_color", $$0 -> $$0.a(dfr.a).a(dfr.b));
   public static final kp<fce> M = a("map_id", $$0 -> $$0.a(fce.a).a(fce.b));
   public static final kp<dfq> N = a("map_decorations", $$0 -> $$0.a(dfq.b).a());
   public static final kp<dfs> O = a("map_post_processing", $$0 -> $$0.a(dfs.d));
   public static final kp<dez> P = a("charged_projectiles", $$0 -> $$0.a(dez.b).a(dez.c).a());
   public static final kp<dey> Q = a("bundle_contents", $$0 -> $$0.a(dey.b).a(dey.c).a());
   public static final kp<der> R = a("potion_contents", $$0 -> $$0.a(der.c).a(der.d).a());
   public static final kp<Float> S = a("potion_duration_scale", $$0 -> $$0.a(bbi.q).a(zk.l).a());
   public static final kp<dfx> T = a("suspicious_stew_effects", $$0 -> $$0.a(dfx.c).a(dfx.d).a());
   public static final kp<dge> U = a("writable_book_content", $$0 -> $$0.a(dge.e).a(dge.f).a());
   public static final kp<dgf> V = a("written_book_content", $$0 -> $$0.a(dgf.i).a(dgf.j).a());
   public static final kp<dlg> W = a("trim", $$0 -> $$0.a(dlg.a).a(dlg.b).a());
   public static final kp<dfh> X = a("debug_stick_state", $$0 -> $$0.a(dfh.b).a());
   public static final kp<dfd> Y = a("entity_data", $$0 -> $$0.a(dfd.c).a(dfd.d));
   public static final kp<dfd> Z = a("bucket_entity_data", $$0 -> $$0.a(dfd.b).a(dfd.d));
   public static final kp<dfd> aa = a("block_entity_data", $$0 -> $$0.a(dfd.c).a(dfd.d));
   public static final kp<dfl> ab = a("instrument", $$0 -> $$0.a(dfl.a).a(dfl.b).a());
   public static final kp<dfu> ac = a("provides_trim_material", $$0 -> $$0.a(dfu.a).a(dfu.b).a());
   public static final kp<dft> ad = a("ominous_bottle_amplifier", $$0 -> $$0.a(dft.d).a(dft.e));
   public static final kp<dda> ae = a("jukebox_playable", $$0 -> $$0.a(dda.a).a(dda.b));
   public static final kp<bae<eao>> af = a("provides_banner_patterns", $$0 -> $$0.a(bae.b(mn.aJ)).a(bae.c(mn.aJ)).a());
   public static final kp<List<amd<dhm<?>>>> ag = a("recipes", $$0 -> $$0.a(dhm.b.listOf()).a());
   public static final kp<dfp> ah = a("lodestone_tracker", $$0 -> $$0.a(dfp.a).a(dfp.b).a());
   public static final kp<dfj> ai = a("firework_explosion", $$0 -> $$0.a(dfj.c).a(dfj.d).a());
   public static final kp<dfk> aj = a("fireworks", $$0 -> $$0.a(dfk.b).a(dfk.c).a());
   public static final kp<dfv> ak = a("profile", $$0 -> $$0.a(dfv.a).a(dfv.b).a());
   public static final kp<ame> al = a("note_block_sound", $$0 -> $$0.a(ame.a).a(ame.b));
   public static final kp<eap> am = a("banner_patterns", $$0 -> $$0.a(eap.b).a(eap.c).a());
   public static final kp<dbt> an = a("base_color", $$0 -> $$0.a(dbt.q).a(dbt.r));
   public static final kp<ech> ao = a("pot_decorations", $$0 -> $$0.a(ech.b).a(ech.c).a());
   public static final kp<dfn> ap = a("container", $$0 -> $$0.a(dfn.b).a(dfn.c).a());
   public static final kp<dev> aq = a("block_state", $$0 -> $$0.a(dev.b).a(dev.c).a());
   public static final kp<deu> ar = a("bees", $$0 -> $$0.a(deu.a).a(deu.b).a());
   public static final kp<bxl> as = a("lock", $$0 -> $$0.a(bxl.b));
   public static final kp<dfw> at = a("container_loot", $$0 -> $$0.a(dfw.a));
   public static final kp<jl<ayy>> au = a("break_sound", $$0 -> $$0.a(ayy.b).a(ayy.d).a());
   public static final kp<jl<cuk>> av = a("villager/variant", $$0 -> $$0.a(cuk.h).a(cuk.i));
   public static final kp<jl<cpm>> aw = a("wolf/variant", $$0 -> $$0.a(cpm.c).a(cpm.d));
   public static final kp<jl<cpk>> ax = a("wolf/sound_variant", $$0 -> $$0.a(cpk.c).a(cpk.d));
   public static final kp<dbt> ay = a("wolf/collar", $$0 -> $$0.a(dbt.q).a(dbt.r));
   public static final kp<cms.v> az = a("fox/variant", $$0 -> $$0.a(cms.v.d).a(cms.v.e));
   public static final kp<cng.a> aA = a("salmon/size", $$0 -> $$0.a(cng.a.e).a(cng.a.f));
   public static final kp<cmz.b> aB = a("parrot/variant", $$0 -> $$0.a(cmz.b.g).a(cmz.b.i));
   public static final kp<cnl.b> aC = a("tropical_fish/pattern", $$0 -> $$0.a(cnl.b.m).a(cnl.b.n));
   public static final kp<dbt> aD = a("tropical_fish/base_color", $$0 -> $$0.a(dbt.q).a(dbt.r));
   public static final kp<dbt> aE = a("tropical_fish/pattern_color", $$0 -> $$0.a(dbt.q).a(dbt.r));
   public static final kp<cmw.a> aF = a("mooshroom/variant", $$0 -> $$0.a(cmw.a.d).a(cmw.a.e));
   public static final kp<cnf.g> aG = a("rabbit/variant", $$0 -> $$0.a(cnf.g.i).a(cnf.g.k));
   public static final kp<jl<cnb>> aH = a("pig/variant", $$0 -> $$0.a(cnb.c).a(cnb.d));
   public static final kp<jl<cmo>> aI = a("cow/variant", $$0 -> $$0.a(cmo.c).a(cmo.d));
   public static final kp<dbw<cmk>> aJ = a("chicken/variant", $$0 -> $$0.a(dbw.a(mn.aN, cmk.c)).a(dbw.a(mn.aN, cmk.d)));
   public static final kp<jl<coe>> aK = a("frog/variant", $$0 -> $$0.a(coe.c).a(coe.d));
   public static final kp<coz> aL = a("horse/variant", $$0 -> $$0.a(coz.h).a(coz.i));
   public static final kp<jl<cqv>> aM = a("painting/variant", $$0 -> $$0.a(cqv.c).a(cqv.d));
   public static final kp<cot.d> aN = a("llama/variant", $$0 -> $$0.a(cot.d.f).a(cot.d.h));
   public static final kp<cnu.e> aO = a("axolotl/variant", $$0 -> $$0.a(cnu.e.h).a(cnu.e.g));
   public static final kp<jl<cmh>> aP = a("cat/variant", $$0 -> $$0.a(cmh.c).a(cmh.d));
   public static final kp<dbt> aQ = a("cat/collar", $$0 -> $$0.a(dbt.q).a(dbt.r));
   public static final kp<dbt> aR = a("sheep/color", $$0 -> $$0.a(dbt.q).a(dbt.r));
   public static final kp<dbt> aS = a("shulker/color", $$0 -> $$0.a(dbt.q).a(dbt.r));
   public static final kn aT = kn.a().a(c, 64).a(j, dfo.a).a(l, djo.a).a(r, 0).a(o, dfm.a).a(k, ddr.a).a(au, ayz.oE).a(q, dfz.c).a();

   public static kp<?> a(jy<kp<?>> $$0) {
      return b;
   }

   private static <T> kp<T> a(String $$0, UnaryOperator<kp.a<T>> $$1) {
      return jy.a(mm.am, $$0, $$1.apply(kp.a()).b());
   }
}
