import java.util.function.BiConsumer;

public record nw(jn.a a) implements nr {
   @Override
   public void generate(BiConsumer<amd<fdo>, fdo.a> $$0) {
      $$0.accept(
         fdf.aX,
         fdo.b()
            .a(
               fdn.a()
                  .a(fhl.a(1.0F))
                  .a(fdw.a(dcz.zw).a(2))
                  .a(fdw.a(dcz.zy).a(2))
                  .a(fdw.a(dcz.rS))
                  .a(fdw.a(dcz.pF))
                  .a(fdw.a(dcz.qv))
                  .a(
                     fdw.a(dcz.xB)
                        .a(
                           ffv.c()
                              .a(bys.p, fhs.a(7.0F, 10.0F))
                              .a(bys.h, fhs.a(7.0F, 10.0F))
                              .a(bys.r, fhs.a(6.0F, 8.0F))
                              .a(bys.o, fhs.a(5.0F, 7.0F))
                              .a(bys.s, fhs.a(10.0F, 20.0F))
                              .a(bys.w, fhs.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         fdf.aY,
         fdo.b()
            .a(
               fdn.a()
                  .a(fhl.a(1.0F))
                  .a(fdw.a(dcz.zv))
                  .a(fdw.a(dcz.zI))
                  .a(fdw.a(dcz.zL))
                  .a(fdw.a(dcz.zP))
                  .a(fdw.a(dcz.pE))
                  .a(fdw.a(dcz.mI))
                  .a(fdw.a(dcz.qz))
                  .a(fdw.a(dcz.pF))
            )
      );
      $$0.accept(
         fdf.aZ,
         fdo.b()
            .a(
               fdn.a()
                  .a(fhl.a(1.0F))
                  .a(fdw.a(dcz.pF).a(2))
                  .a(fdw.a(dcz.qB).a(2))
                  .a(fdw.a(dcz.pV).a(2))
                  .a(fdw.a(dcz.fs).a(2))
                  .a(fdw.a(dcz.rS).a(2))
                  .a(fdw.a(dcz.sL).a(2))
                  .a(fdw.a(dcz.sS).a(2))
                  .a(fdw.a(dcz.sK).a(2))
                  .a(fdw.a(dcz.sH).a(2))
                  .a(fdw.a(dcz.sI).a(2))
                  .a(fdw.a(dcz.yO).a(2))
                  .a(fdw.a(dcz.yN).a(2))
                  .a(fdw.a(dcz.yK).a(2))
                  .a(fdw.a(dcz.yM).a(2))
                  .a(fdw.a(dcz.iZ))
                  .a(fdw.a(dcz.jd))
                  .a(fdw.a(dcz.ji))
                  .a(fdw.a(dcz.ja))
                  .a(fdw.a(dcz.jl))
                  .a(fdw.a(dcz.jb))
                  .a(fdw.a(dcz.jh))
                  .a(fdw.a(dcz.ru))
                  .a(fdw.a(dcz.rt))
                  .a(fdw.a(dcz.tH))
                  .a(fdw.a(dcz.pC))
                  .a(fdw.a(dcz.qA))
                  .a(fdw.a(dcz.wO))
                  .a(fdw.a(dcz.cZ))
                  .a(fdw.a(dcz.vG))
                  .a(fdw.a(dcz.qx))
                  .a(fdw.a(dcz.wn))
            )
      );
      $$0.accept(
         fdf.ba,
         fdo.b()
            .a(
               fdn.a()
                  .a(fhl.a(1.0F))
                  .a(fdw.a(dcz.zz))
                  .a(fdw.a(dcz.zA))
                  .a(fdw.a(dcz.zD))
                  .a(fdw.a(dcz.zF))
                  .a(fdw.a(dcz.zG))
                  .a(fdw.a(dcz.zH))
                  .a(fdw.a(dcz.zN))
                  .a(fdw.a(dcz.zn))
                  .a(fdw.a(dcz.zq))
                  .a(fdw.a(dcz.zo))
                  .a(fdw.a(dcz.zr))
                  .a(fdw.a(dcz.xr))
            )
      );
      $$0.accept(
         fdf.bb,
         fdo.b()
            .a(
               fdn.a()
                  .a(fhl.a(1.0F))
                  .a(fdw.a(dcz.zu))
                  .a(fdw.a(dcz.zO))
                  .a(fdw.a(dcz.zQ))
                  .a(fdw.a(dcz.kU))
                  .a(fdw.a(dcz.qj))
                  .a(fdw.a(dcz.pF).a(2))
                  .a(fdw.a(dcz.qB).a(2))
                  .a(fdw.a(dcz.pV).a(2))
                  .a(fdw.a(dcz.pC).a(2))
                  .a(fdw.a(dcz.tH).a(2))
            )
      );
      $$0.accept(
         fdf.bc,
         fdo.b()
            .a(
               fdn.a()
                  .a(fhl.a(1.0F))
                  .a(fdw.a(dcz.zx))
                  .a(fdw.a(dcz.zB))
                  .a(fdw.a(dcz.zJ))
                  .a(fdw.a(dcz.zK))
                  .a(fdw.a(dcz.qj))
                  .a(fdw.a(dcz.pF).a(2))
                  .a(fdw.a(dcz.qB).a(2))
                  .a(fdw.a(dcz.pV).a(2))
                  .a(fdw.a(dcz.pC).a(2))
                  .a(fdw.a(dcz.tH).a(2))
            )
      );
   }
}
