import java.util.List;

public class ru {
   public static final amd<ems<?, ?>> a = rr.a("ore_magma");
   public static final amd<ems<?, ?>> b = rr.a("ore_soul_sand");
   public static final amd<ems<?, ?>> c = rr.a("ore_nether_gold");
   public static final amd<ems<?, ?>> d = rr.a("ore_quartz");
   public static final amd<ems<?, ?>> e = rr.a("ore_gravel_nether");
   public static final amd<ems<?, ?>> f = rr.a("ore_blackstone");
   public static final amd<ems<?, ?>> g = rr.a("ore_dirt");
   public static final amd<ems<?, ?>> h = rr.a("ore_gravel");
   public static final amd<ems<?, ?>> i = rr.a("ore_granite");
   public static final amd<ems<?, ?>> j = rr.a("ore_diorite");
   public static final amd<ems<?, ?>> k = rr.a("ore_andesite");
   public static final amd<ems<?, ?>> l = rr.a("ore_tuff");
   public static final amd<ems<?, ?>> m = rr.a("ore_coal");
   public static final amd<ems<?, ?>> n = rr.a("ore_coal_buried");
   public static final amd<ems<?, ?>> o = rr.a("ore_iron");
   public static final amd<ems<?, ?>> p = rr.a("ore_iron_small");
   public static final amd<ems<?, ?>> q = rr.a("ore_gold");
   public static final amd<ems<?, ?>> r = rr.a("ore_gold_buried");
   public static final amd<ems<?, ?>> s = rr.a("ore_redstone");
   public static final amd<ems<?, ?>> t = rr.a("ore_diamond_small");
   public static final amd<ems<?, ?>> u = rr.a("ore_diamond_medium");
   public static final amd<ems<?, ?>> v = rr.a("ore_diamond_large");
   public static final amd<ems<?, ?>> w = rr.a("ore_diamond_buried");
   public static final amd<ems<?, ?>> x = rr.a("ore_lapis");
   public static final amd<ems<?, ?>> y = rr.a("ore_lapis_buried");
   public static final amd<ems<?, ?>> z = rr.a("ore_infested");
   public static final amd<ems<?, ?>> A = rr.a("ore_emerald");
   public static final amd<ems<?, ?>> B = rr.a("ore_ancient_debris_large");
   public static final amd<ems<?, ?>> C = rr.a("ore_ancient_debris_small");
   public static final amd<ems<?, ?>> D = rr.a("ore_copper_small");
   public static final amd<ems<?, ?>> E = rr.a("ore_copper_large");
   public static final amd<ems<?, ?>> F = rr.a("ore_clay");

   public static void a(qq<ems<?, ?>> $$0) {
      eyu $$1 = new ezc(azo.bi);
      eyu $$2 = new ezc(azo.bj);
      eyu $$3 = new ezc(azo.bk);
      eyu $$4 = new eyc(dqb.em);
      eyu $$5 = new ezc(azo.bl);
      List<epu.a> $$6 = List.of(epu.a($$2, dqb.S.m()), epu.a($$3, dqb.T.m()));
      List<epu.a> $$7 = List.of(epu.a($$2, dqb.Q.m()), epu.a($$3, dqb.R.m()));
      List<epu.a> $$8 = List.of(epu.a($$2, dqb.cI.m()), epu.a($$3, dqb.cJ.m()));
      List<epu.a> $$9 = List.of(epu.a($$2, dqb.aY.m()), epu.a($$3, dqb.aZ.m()));
      List<epu.a> $$10 = List.of(epu.a($$2, dqb.rJ.m()), epu.a($$3, dqb.rK.m()));
      List<epu.a> $$11 = List.of(epu.a($$2, dqb.U.m()), epu.a($$3, dqb.V.m()));
      rr.a($$0, a, enh.J, new epu($$4, dqb.lp.m(), 33));
      rr.a($$0, b, enh.J, new epu($$4, dqb.en.m(), 12));
      rr.a($$0, c, enh.J, new epu($$4, dqb.W.m(), 10));
      rr.a($$0, d, enh.J, new epu($$4, dqb.hC.m(), 14));
      rr.a($$0, e, enh.J, new epu($$4, dqb.O.m(), 33));
      rr.a($$0, f, enh.J, new epu($$4, dqb.qa.m(), 33));
      rr.a($$0, g, enh.J, new epu($$1, dqb.j.m(), 33));
      rr.a($$0, h, enh.J, new epu($$1, dqb.O.m(), 33));
      rr.a($$0, i, enh.J, new epu($$1, dqb.c.m(), 64));
      rr.a($$0, j, enh.J, new epu($$1, dqb.e.m(), 64));
      rr.a($$0, k, enh.J, new epu($$1, dqb.g.m(), 64));
      rr.a($$0, l, enh.J, new epu($$1, dqb.ri.m(), 64));
      rr.a($$0, m, enh.J, new epu($$11, 17));
      rr.a($$0, n, enh.J, new epu($$11, 17, 0.5F));
      rr.a($$0, o, enh.J, new epu($$6, 9));
      rr.a($$0, p, enh.J, new epu($$6, 4));
      rr.a($$0, q, enh.J, new epu($$7, 9));
      rr.a($$0, r, enh.J, new epu($$7, 9, 0.5F));
      rr.a($$0, s, enh.J, new epu(List.of(epu.a($$2, dqb.dY.m()), epu.a($$3, dqb.dZ.m())), 8));
      rr.a($$0, t, enh.J, new epu($$8, 4, 0.5F));
      rr.a($$0, v, enh.J, new epu($$8, 12, 0.7F));
      rr.a($$0, w, enh.J, new epu($$8, 8, 1.0F));
      rr.a($$0, u, enh.J, new epu($$8, 8, 0.5F));
      rr.a($$0, x, enh.J, new epu($$9, 7));
      rr.a($$0, y, enh.J, new epu($$9, 7, 1.0F));
      rr.a($$0, z, enh.J, new epu(List.of(epu.a($$2, dqb.ff.m()), epu.a($$3, dqb.tO.m())), 9));
      rr.a($$0, A, enh.J, new epu(List.of(epu.a($$2, dqb.gd.m()), epu.a($$3, dqb.ge.m())), 3));
      rr.a($$0, B, enh.ag, new epu($$5, dqb.pS.m(), 3, 1.0F));
      rr.a($$0, C, enh.ag, new epu($$5, dqb.pS.m(), 2, 1.0F));
      rr.a($$0, D, enh.J, new epu($$10, 10));
      rr.a($$0, E, enh.J, new epu($$10, 20));
      rr.a($$0, F, enh.J, new epu($$1, dqb.ei.m(), 33));
   }
}
