import java.util.List;

public class sh {
   public static final amd<euc> a = sg.a("crimson_fungi");
   public static final amd<euc> b = sg.a("warped_fungi");
   public static final amd<euc> c = sg.a("oak_checked");
   public static final amd<euc> d = sg.a("dark_oak_checked");
   public static final amd<euc> e = sg.a("pale_oak_checked");
   public static final amd<euc> f = sg.a("pale_oak_creaking_checked");
   public static final amd<euc> g = sg.a("birch_checked");
   public static final amd<euc> h = sg.a("acacia_checked");
   public static final amd<euc> i = sg.a("spruce_checked");
   public static final amd<euc> j = sg.a("mangrove_checked");
   public static final amd<euc> k = sg.a("cherry_checked");
   public static final amd<euc> l = sg.a("pine_on_snow");
   public static final amd<euc> m = sg.a("spruce_on_snow");
   public static final amd<euc> n = sg.a("pine_checked");
   public static final amd<euc> o = sg.a("jungle_tree");
   public static final amd<euc> p = sg.a("fancy_oak_checked");
   public static final amd<euc> q = sg.a("mega_jungle_tree_checked");
   public static final amd<euc> r = sg.a("mega_spruce_checked");
   public static final amd<euc> s = sg.a("mega_pine_checked");
   public static final amd<euc> t = sg.a("tall_mangrove_checked");
   public static final amd<euc> u = sg.a("jungle_bush");
   public static final amd<euc> v = sg.a("super_birch_bees_0002");
   public static final amd<euc> w = sg.a("super_birch_bees");
   public static final amd<euc> x = sg.a("oak_bees_0002_leaf_litter");
   public static final amd<euc> y = sg.a("oak_bees_002");
   public static final amd<euc> z = sg.a("birch_bees_0002");
   public static final amd<euc> A = sg.a("birch_bees_0002_leaf_litter");
   public static final amd<euc> B = sg.a("birch_bees_002");
   public static final amd<euc> C = sg.a("fancy_oak_bees_0002_leaf_litter");
   public static final amd<euc> D = sg.a("fancy_oak_bees_002");
   public static final amd<euc> E = sg.a("fancy_oak_bees");
   public static final amd<euc> F = sg.a("cherry_bees_005");
   public static final amd<euc> G = sg.a("oak_leaf_litter");
   public static final amd<euc> H = sg.a("dark_oak_leaf_litter");
   public static final amd<euc> I = sg.a("birch_leaf_litter");
   public static final amd<euc> J = sg.a("fancy_oak_leaf_litter");
   public static final amd<euc> K = sg.a("fallen_oak_tree");
   public static final amd<euc> L = sg.a("fallen_birch_tree");
   public static final amd<euc> M = sg.a("fallen_super_birch_tree");
   public static final amd<euc> N = sg.a("fallen_spruce_tree");
   public static final amd<euc> O = sg.a("fallen_jungle_tree");

   public static void a(qq<euc> $$0) {
      jm<ems<?, ?>> $$1 = $$0.a(mn.aP);
      jl<ems<?, ?>> $$2 = $$1.b(rw.a);
      jl<ems<?, ?>> $$3 = $$1.b(rw.c);
      jl<ems<?, ?>> $$4 = $$1.b(rw.g);
      jl<ems<?, ?>> $$5 = $$1.b(rw.h);
      jl<ems<?, ?>> $$6 = $$1.b(rw.i);
      jl<ems<?, ?>> $$7 = $$1.b(rw.k);
      jl<ems<?, ?>> $$8 = $$1.b(rw.l);
      jl<ems<?, ?>> $$9 = $$1.b(rw.m);
      jl<ems<?, ?>> $$10 = $$1.b(rw.n);
      jl<ems<?, ?>> $$11 = $$1.b(rw.A);
      jl<ems<?, ?>> $$12 = $$1.b(rw.C);
      jl<ems<?, ?>> $$13 = $$1.b(rw.o);
      jl<ems<?, ?>> $$14 = $$1.b(rw.p);
      jl<ems<?, ?>> $$15 = $$1.b(rw.q);
      jl<ems<?, ?>> $$16 = $$1.b(rw.s);
      jl<ems<?, ?>> $$17 = $$1.b(rw.t);
      jl<ems<?, ?>> $$18 = $$1.b(rw.u);
      jl<ems<?, ?>> $$19 = $$1.b(rw.B);
      jl<ems<?, ?>> $$20 = $$1.b(rw.y);
      jl<ems<?, ?>> $$21 = $$1.b(rw.v);
      jl<ems<?, ?>> $$22 = $$1.b(rw.w);
      jl<ems<?, ?>> $$23 = $$1.b(rw.D);
      jl<ems<?, ?>> $$24 = $$1.b(rw.E);
      jl<ems<?, ?>> $$25 = $$1.b(rw.G);
      jl<ems<?, ?>> $$26 = $$1.b(rw.H);
      jl<ems<?, ?>> $$27 = $$1.b(rw.I);
      jl<ems<?, ?>> $$28 = $$1.b(rw.K);
      jl<ems<?, ?>> $$29 = $$1.b(rw.L);
      jl<ems<?, ?>> $$30 = $$1.b(rw.N);
      jl<ems<?, ?>> $$31 = $$1.b(rw.O);
      jl<ems<?, ?>> $$32 = $$1.b(rw.P);
      jl<ems<?, ?>> $$33 = $$1.b(rw.Q);
      jl<ems<?, ?>> $$34 = $$1.b(rw.R);
      jl<ems<?, ?>> $$35 = $$1.b(rw.S);
      jl<ems<?, ?>> $$36 = $$1.b(rw.T);
      jl<ems<?, ?>> $$37 = $$1.b(rw.W);
      jl<ems<?, ?>> $$38 = $$1.b(rw.X);
      jl<ems<?, ?>> $$39 = $$1.b(rw.V);
      jl<ems<?, ?>> $$40 = $$1.b(rw.U);
      sg.a($$0, a, $$2, ett.a(8), etq.a());
      sg.a($$0, b, $$3, ett.a(8), etq.a());
      sg.a($$0, c, $$4, sg.a(dqb.z));
      sg.a($$0, d, $$5, sg.a(dqb.F));
      sg.a($$0, e, $$6, sg.a(dqb.G));
      sg.a($$0, f, $$7, sg.a(dqb.G));
      sg.a($$0, g, $$8, sg.a(dqb.B));
      sg.a($$0, h, $$9, sg.a(dqb.D));
      sg.a($$0, i, $$10, sg.a(dqb.A));
      sg.a($$0, j, $$11, sg.a(dqb.H));
      sg.a($$0, k, $$12, sg.a(dqb.E));
      elh $$41 = elh.a(jh.a.q(), dqb.ef, dqb.ry);
      List<euf> $$42 = List.of(etv.a(jh.b, elh.a(elh.a(dqb.ry)), 8), etr.a($$41));
      sg.a($$0, l, $$13, $$42);
      sg.a($$0, m, $$10, $$42);
      sg.a($$0, n, $$13, sg.a(dqb.A));
      sg.a($$0, o, $$14, sg.a(dqb.C));
      sg.a($$0, p, $$15, sg.a(dqb.z));
      sg.a($$0, q, $$16, sg.a(dqb.C));
      sg.a($$0, r, $$17, sg.a(dqb.A));
      sg.a($$0, s, $$18, sg.a(dqb.A));
      sg.a($$0, t, $$19, sg.a(dqb.H));
      sg.a($$0, u, $$20, sg.a(dqb.z));
      sg.a($$0, v, $$21, sg.a(dqb.B));
      sg.a($$0, w, $$22, sg.a(dqb.B));
      sg.a($$0, x, $$23, sg.a(dqb.z));
      sg.a($$0, y, $$24, sg.a(dqb.z));
      sg.a($$0, z, $$25, sg.a(dqb.B));
      sg.a($$0, A, $$26, sg.a(dqb.B));
      sg.a($$0, B, $$27, sg.a(dqb.B));
      sg.a($$0, C, $$28, sg.a(dqb.z));
      sg.a($$0, D, $$29, sg.a(dqb.z));
      sg.a($$0, E, $$30, sg.a(dqb.z));
      sg.a($$0, F, $$31, sg.a(dqb.E));
      sg.a($$0, G, $$32, sg.a(dqb.z));
      sg.a($$0, H, $$33, sg.a(dqb.F));
      sg.a($$0, I, $$34, sg.a(dqb.B));
      sg.a($$0, J, $$35, sg.a(dqb.z));
      sg.a($$0, K, $$36, sg.a(dqb.z));
      sg.a($$0, L, $$37, sg.a(dqb.B));
      sg.a($$0, M, $$38, sg.a(dqb.B));
      sg.a($$0, N, $$39, sg.a(dqb.A));
      sg.a($$0, O, $$40, sg.a(dqb.C));
   }
}
